version: "3.7"

services:
  
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - volumes-db:/data/postgres
 
  api:
    build: .
    container_name: rentx_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database  


volumes:
  volumes-db:
    driver: local
