version: "3.9"

services:

    database:
        image: postgres
        container_name: 'rentx-database'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=rentx
            - POSTGRES_PASSWORD=rentx
            - POSTGRES_DB=rentx
        volumes:
            - ./docker/postgres:/var/lib/postgresql
        networks:
            - default

#    api:
#        build: .
#        container_name: 'rentx-api'
#        ports:
#            - '3333:3333'
#            - '9229:9229'
#        volumes:
#            - .:/usr/app
#        links:
#            - database
#            - redis
#        depends_on:
#            - database
#            - redis
#        networks:
#            - default

    redis:
        image: redis:alpine
        container_name: 'rentx-redis'
        ports:
            - '6379:6379'
        networks:
            - default
